CREATE TABLE pessoa(
	codigo	BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    nome 	VARCHAR(50)	NOT NULL,
    ativo 	BOOLEAN	NOT NULL,
    logradouro	VARCHAR(50),
    numero	VARCHAR(5),
    complemento	VARCHAR(20),
    bairro	VARCHAR(20),
    cep		VARCHAR(10),
    cidade 	VARCHAR(20),
    estado	VARCHAR(2)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO pessoa (nome, 
					ativo, 
                    logradouro, 
                    numero, 
                    complemento, 
                    bairro, 
                    cep, 
                    cidade, 
                    estado) 
			VALUES ('Gabriel Cezar',
					true,
                    'Rua abcd',
                    '123',
                    'Casa Roxa',
                    'Santa Mônica',
                    '12.345-678',
                    'Uberlândia',
                    'MG');
INSERT INTO pessoa (nome, 
					ativo, 
                    logradouro, 
                    numero, 
                    complemento, 
                    bairro, 
                    cep, 
                    cidade, 
                    estado) 
			VALUES ('Jose João',
					false,
                    'Rua xico xavier',
                    '1456',
                    'Em frente ao Campo',
                    'Roosevelt',
                    '12.345-678',
                    'Uberlândia',
                    'MG');
INSERT INTO pessoa (nome, 
					ativo, 
                    logradouro, 
                    numero, 
                    complemento, 
                    bairro, 
                    cep, 
                    cidade, 
                    estado) 
			VALUES ('Maria José',
					false,
                    'Rua Tiradentes',
                    '785',
                    'Portão Rosa',
                    'Brasil',
                    '12.345-678',
                    'Uberlândia',
                    'MG');
INSERT INTO pessoa (nome, 
					ativo, 
                    logradouro, 
                    numero, 
                    complemento, 
                    bairro, 
                    cep, 
                    cidade, 
                    estado) 
			VALUES ('Maria das Dores',
					true,
                    'Rua José de Abreu',
                    '896',
                    'Muro xapiscado',
                    'Carajas',
                    '12.345-678',
                    'Uberlândia',
                    'MG');
INSERT INTO pessoa (nome, 
					ativo, 
                    logradouro, 
                    numero, 
                    complemento, 
                    bairro, 
                    cep, 
                    cidade, 
                    estado) 
			VALUES ('Euclides Soares',
					false,
                    'Avenida Zumbi de Palmares',
                    '83',
                    'apto 501',
                    'Almeida',
                    '12.345-678',
                    'Uberlândia',
                    'MG');
INSERT INTO pessoa (nome, 
					ativo, 
                    logradouro, 
                    numero, 
                    complemento, 
                    bairro, 
                    cep, 
                    cidade, 
                    estado) 
			VALUES ('Rafael Moreira',
					true,
                    'Rua Kurt Cobain',
                    '777',
                    'Muro Graffitado',
                    'Brasil',
                    '12.345-678',
                    'Uberlândia',
                    'MG');
INSERT INTO pessoa (nome, 
					ativo, 
                    logradouro, 
                    numero, 
                    complemento, 
                    bairro, 
                    cep, 
                    cidade, 
                    estado) 
			VALUES ('Mario Loiola',
					true,
                    'Rua Raio de Luz',
                    '325',
                    'Grade Verde',
                    'Nova Lima',
                    '12.345-678',
                    'Uberlândia',
                    'MG');